id: I02F2CFFB
legacy_id: P000329
ocr_import_info:
  bdrc_scan_id: W2DB25450
  source: bdrc
  ocr_info:
    timestamp: '2020-03-12T19:21:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T16:39:05.014849+00:00'
last_modified: 2022-09-03 00:47:29.875674
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2DB25450
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2DB25450
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: a glossary of the tribes and castes of the punjab and north-west frontier
    province
  author: rose, h. a. (horace arthur)
statistics:
  ocr_word_mean_confidence_index: 0.9468259315193506
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1PD36343:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD36343
      total_pages: 582
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD36343.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9469040666166356
    legacy_id: v001
  I1PD36344:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD36344
      total_pages: 542
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1PD36344.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9467391997854955
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
