id: opecha:P000329
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB25450
  title: ཨ་གློསསརཡ་ཨོཕ༹་ཐེ་ཏྲིབེས་ཨནད་ཅསྟེས་ཨོཕ༹་ཐེ་པུནཇབ་ཨནད་ནོརཐ-ཝེསཏ་ཕ༹ྲོནཏིཨེར་པྲོབི༹ནཅེ་
  volume: ''
  author: ''
